/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedKeuanganRouteImport } from './routes/_authenticated/keuangan'
import { Route as AuthenticatedKegiatanRouteImport } from './routes/_authenticated/kegiatan'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDiskusiIndexRouteImport } from './routes/_authenticated/diskusi/index'
import { Route as AuthenticatedMembersAddRouteImport } from './routes/_authenticated/members/add'
import { Route as AuthenticatedDiskusiIdRouteImport } from './routes/_authenticated/diskusi/$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKeuanganRoute = AuthenticatedKeuanganRouteImport.update({
  id: '/keuangan',
  path: '/keuangan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKegiatanRoute = AuthenticatedKegiatanRouteImport.update({
  id: '/kegiatan',
  path: '/kegiatan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiskusiIndexRoute =
  AuthenticatedDiskusiIndexRouteImport.update({
    id: '/diskusi/',
    path: '/diskusi/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembersAddRoute = AuthenticatedMembersAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AuthenticatedMembersRoute,
} as any)
const AuthenticatedDiskusiIdRoute = AuthenticatedDiskusiIdRouteImport.update({
  id: '/diskusi/$id',
  path: '/diskusi/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/events': typeof AuthenticatedEventsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/kegiatan': typeof AuthenticatedKegiatanRoute
  '/keuangan': typeof AuthenticatedKeuanganRoute
  '/members': typeof AuthenticatedMembersRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/diskusi/$id': typeof AuthenticatedDiskusiIdRoute
  '/members/add': typeof AuthenticatedMembersAddRoute
  '/diskusi/': typeof AuthenticatedDiskusiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/events': typeof AuthenticatedEventsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/kegiatan': typeof AuthenticatedKegiatanRoute
  '/keuangan': typeof AuthenticatedKeuanganRoute
  '/members': typeof AuthenticatedMembersRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/diskusi/$id': typeof AuthenticatedDiskusiIdRoute
  '/members/add': typeof AuthenticatedMembersAddRoute
  '/diskusi': typeof AuthenticatedDiskusiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/kegiatan': typeof AuthenticatedKegiatanRoute
  '/_authenticated/keuangan': typeof AuthenticatedKeuanganRoute
  '/_authenticated/members': typeof AuthenticatedMembersRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/diskusi/$id': typeof AuthenticatedDiskusiIdRoute
  '/_authenticated/members/add': typeof AuthenticatedMembersAddRoute
  '/_authenticated/diskusi/': typeof AuthenticatedDiskusiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/events'
    | '/home'
    | '/kegiatan'
    | '/keuangan'
    | '/members'
    | '/profile'
    | '/diskusi/$id'
    | '/members/add'
    | '/diskusi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/events'
    | '/home'
    | '/kegiatan'
    | '/keuangan'
    | '/members'
    | '/profile'
    | '/diskusi/$id'
    | '/members/add'
    | '/diskusi'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/events'
    | '/_authenticated/home'
    | '/_authenticated/kegiatan'
    | '/_authenticated/keuangan'
    | '/_authenticated/members'
    | '/_authenticated/profile'
    | '/_authenticated/diskusi/$id'
    | '/_authenticated/members/add'
    | '/_authenticated/diskusi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keuangan': {
      id: '/_authenticated/keuangan'
      path: '/keuangan'
      fullPath: '/keuangan'
      preLoaderRoute: typeof AuthenticatedKeuanganRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kegiatan': {
      id: '/_authenticated/kegiatan'
      path: '/kegiatan'
      fullPath: '/kegiatan'
      preLoaderRoute: typeof AuthenticatedKegiatanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diskusi/': {
      id: '/_authenticated/diskusi/'
      path: '/diskusi'
      fullPath: '/diskusi/'
      preLoaderRoute: typeof AuthenticatedDiskusiIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members/add': {
      id: '/_authenticated/members/add'
      path: '/add'
      fullPath: '/members/add'
      preLoaderRoute: typeof AuthenticatedMembersAddRouteImport
      parentRoute: typeof AuthenticatedMembersRoute
    }
    '/_authenticated/diskusi/$id': {
      id: '/_authenticated/diskusi/$id'
      path: '/diskusi/$id'
      fullPath: '/diskusi/$id'
      preLoaderRoute: typeof AuthenticatedDiskusiIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedMembersRouteChildren {
  AuthenticatedMembersAddRoute: typeof AuthenticatedMembersAddRoute
}

const AuthenticatedMembersRouteChildren: AuthenticatedMembersRouteChildren = {
  AuthenticatedMembersAddRoute: AuthenticatedMembersAddRoute,
}

const AuthenticatedMembersRouteWithChildren =
  AuthenticatedMembersRoute._addFileChildren(AuthenticatedMembersRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedKegiatanRoute: typeof AuthenticatedKegiatanRoute
  AuthenticatedKeuanganRoute: typeof AuthenticatedKeuanganRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedDiskusiIdRoute: typeof AuthenticatedDiskusiIdRoute
  AuthenticatedDiskusiIndexRoute: typeof AuthenticatedDiskusiIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedKegiatanRoute: AuthenticatedKegiatanRoute,
  AuthenticatedKeuanganRoute: AuthenticatedKeuanganRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedDiskusiIdRoute: AuthenticatedDiskusiIdRoute,
  AuthenticatedDiskusiIndexRoute: AuthenticatedDiskusiIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
